export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';

export const FETCH_RESULT_SUCCESS = 'FETCH_RESULT_SUCCESS';
export const FETCH_RESULT_FAILURE = 'FETCH_RESULT_FAILURE';

export const DELETE_RESULT_SUCCESS = 'DELETE_RESULT_SUCCESS';
export const DELETE_RESULT_FAILURE = 'DELETE_RESULT_FAILURE';

export const FETCH_OFFICE_SUCCESS = 'FETCH_OFFICE_SUCCESS';
export const FETCH_OFFICE_FAILURE = 'FETCH_OFFICE_FAILURE';

export const FETCH_PARTY_SUCCESS = 'FETCH_PARTY_SUCCESS';
export const FETCH_PARTY_FAILURE = 'FETCH_PARTY_FAILURE';

export const REGISTER_PARTY_SUCCESS = 'REGISTER_PARTY_SUCCESS';
export const  REGISTER_PARTY_FAILURE = 'REGISTER_PARTY_FAILURE';
export const  MODIFY_PARTY_SUCCESS = 'MODIFY_PARTY_SUCCESS';
export const  MODIFY_PARTY_FAILURE = 'MODIFY_PARTY_FAILURE';
export const  DELETE_PARTY_SUCCESS = 'DELETE_PARTY_SUCCESS';
export const  DELETE_PARTY_FAILURE = 'DELETE_PARTY_FAILURE';